### ISSUE TITLE
Allow the command "render" to be called within the subdirs of a project dir

### ISSUE THREAD

**Issue by derdon** [derdon/swsg#2]
It should also print a useful error message if this command is entered in a path where no swsg project can be found.

**Comment by Trundle** [comment]
My quick attempt for allowing the render command to be called within subdirs (see http://bpaste.net/show/11920/ for a downloadable/highlighted version). It only allows that the parent dir is the project dir (IOW: only one level up), but that can be easily changed.

<pre>
diff --git a/swsg/cli.py b/swsg/cli.py
index 961cac5..bf168ec 100755
--- a/swsg/cli.py
+++ b/swsg/cli.py
@@ -155,7 +155,7 @@ def change_config(args):
 
 def render(args):
     # the project's directory is the current working directory
-    project = get_project_by_path(getcwd())
+    project = get_project_by_path(getcwd(), look_at_parent_dir=True)
     for output_path, output in project.render():
         with codecs.open(output_path, 'w', 'utf-8') as fp:
             fp.write(output)
diff --git a/swsg/projects.py b/swsg/projects.py
index f5d1154..b42a0ea 100644
--- a/swsg/projects.py
+++ b/swsg/projects.py
@@ -300,9 +300,17 @@ def list_project_instances(projects_file_name=DEFAULT_PROJECTS_FILE_NAME):
 
 
 def get_project_by_path(project_dir,
-    projects_file_name=DEFAULT_PROJECTS_FILE_NAME):
+    projects_file_name=DEFAULT_PROJECTS_FILE_NAME,
+    look_at_parent_dir=False):
     full_project_path = os.path.abspath(project_dir)
     with contextlib.closing(shelve.open(projects_file_name)) as p:
+        if look_at_parent_dir:
+            # Look whether some parent directory is a project
+            key_func = lambda x: os.path.commonprefix([x, full_project_path])
+            possible_paths = sorted(p, key=key_func, reverse=True)
+            if (possible_paths and
+                os.path.dirname(full_project_path) == possible_paths[0]):
+                full_project_path = possible_paths[0]
         try:
             project = p[full_project_path]
         except KeyError:
</pre>

**Comment by derdon** [comment]
Thanks for the patch, Trundle. The commit can be found at https://github.com/derdon/swsg/commit/93f685a47bb55bfb84d4d1ccb129c22ad697463c
